[project]
name = "dataset-olist"
version = "0.1.0"
description = "Mentoring - Exercise 1 - Data Storage"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "luigi==3.5.0",
    "pandas==2.2.1",
    "psycopg2-binary>=2.9.11",
    "python-dotenv==1.0.1",
    "sentry-sdk==1.43.0",
    "sqlalchemy==2.0.28",
]
